# Generated by Django 3.1.6 on 2022-07-27 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=64, unique=True)),
                ('teamID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField()),
                ('teamAdmin', models.BooleanField(default=False)),
                ('avatar', models.ImageField(upload_to='')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iTracker.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectName', models.CharField(max_length=100)),
                ('description', models.TextField(default='Project Description', max_length=1024)),
                ('Progressbar', models.IntegerField(default=0)),
                ('taskID', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('lastUpdate', models.DateTimeField(auto_now=True)),
                ('doing', models.BooleanField(default=False)),
                ('relatedTaskID', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iTracker.userextended')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iTracker.team')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss', models.TextField(default='', max_length=1024)),
                ('time', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='iTracker.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iTracker.userextended')),
            ],
        ),
    ]
