# Generated by Django 3.1.6 on 2022-06-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='doing',
            field=models.BooleanField(default=False),
        ),
    ]
