# Generated by Django 3.1.6 on 2022-07-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextended',
            name='avatar',
            field=models.ImageField(default='static/iTrcker/images/default.jpg', upload_to='static/iTracker/images'),
        ),
    ]
