# Generated by Django 3.1.6 on 2022-06-15 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iTracker', '0010_auto_20220615_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextended',
            old_name='teamMember',
            new_name='team',
        ),
    ]
