# Generated by Django 3.1.6 on 2022-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iTracker', '0011_auto_20220615_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='teamAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
