# Generated by Django 3.1.6 on 2022-06-23 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iTracker', '0013_auto_20220622_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='discuss',
        ),
    ]
